---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: check-pr-labels
spec:
  steps:
    - name: check-labels
      image: curlimages/curl:latest
      env:
        - name: PR_NUMBER
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pac.test.appstudio.openshift.io/pull-request']
      script: |
        #!/bin/sh
        set -e

        echo "[INFO] Checking labels for PR: $PR_NUMBER"
        
        if [ -z "$PR_NUMBER" ]; then
          echo "[INFO] PR_NUMBER is empty. Skipping label check."
          exit 0
        fi

        LABELS=$(curl -s https://api.github.com/repos/project-koku/koku/issues/$PR_NUMBER/labels | grep -o '"name": *"[^"]*"' | cut -d '"' -f4)

        echo "[INFO] PR Labels: $LABELS"

        if ! echo "$LABELS" | grep -q "testing-cicd"; then
          echo "[INFO] No test label found. Skipping label check logic."
          exit 0
        fi

        if echo "$LABELS" | grep -q "run-jenkins-tests"; then
          echo "[INFO] PR labeled to run Jenkins tests. Skipping Tekton pipeline."
          exit 0
        fi

        if echo "$LABELS" | grep -q "smokes-required"; then
          if ! echo "$LABELS" | grep -q "smoke-tests$"; then
            echo "[INFO] Missing required smoke test label with smokes-required."
            exit 1
          fi
        fi

        echo "[INFO] Label check passed."
        exit 0