apiVersion: tekton.dev/v1
kind: Task
metadata:
  namespace: cost-mgmt-dev-tenant
  name: debug

spec:
  params:
    - name: BONFIRE_IMAGE
      type: string

    - name: SNAPSHOT
      type: string

    - name: REF_ENV
      type: string

    - name: PIPELINE_RUN_NAME
      type: string

    - name: PIPELINE_RUN_UID
      type: string

  steps:
    - name: show-some-things
      image: $(params.BONFIRE_IMAGE)
      onError: continue
      env:
        - name: PR_NUMBER
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pac.test.appstudio.openshift.io/pull-request']

        - name: CHECK_RUN_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pac.test.appstudio.openshift.io/check-run-id']

        - name: NOPE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pac.test.appstudio.openshift.io/nope]

        - name: SNAPSHOT
          value: $(params.SNAPSHOT)

        - name: REF_ENV
          value: $(params.REF_ENV)

      script: |
        #!/usr/bin/env python

        import os

        check_run_id = os.environ.get('CHECK_RUN_ID')
        nope = os.environ.get('nope')
        if check_run_id:
          print("Got check run ID")

        if nope:
          print('Got non-existant field')

        print(check_run_id)
        print(type(check_run_id))

        print(nope)
        print(type(nope))


