apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: teardown
spec:
  params:
    - name: NS
      type: string
      description: Namespace name to release
    - name: NS_REQUESTER
      type: string
      description: The name of the person/pipeline that requested the namespace
    - name: EPHEMERAL_ENV_PROVIDER_SECRET
      type: string
      default: ephemeral-env-provider
      description: "Secret for connecting to ephemeral env provider cluster"
    - name: IQE_POD
      type: string
      description: The name of the IQE Pod
  volumes:
    - name: artifacts
      emptyDir: {}
  steps:
    - name: collect-logs
      image: quay.io/redhat-user-workloads/rhtap-migration-tenant/bonfire-cicd-tools/cicd-tools:c66a92daeb5b9ed409e3006696572c4e62252fd4
      env:
        - name: OC_LOGIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.EPHEMERAL_ENV_PROVIDER_SECRET)
              key: token
        - name: OC_LOGIN_SERVER
          valueFrom:
            secretKeyRef:
              name: $(params.EPHEMERAL_ENV_PROVIDER_SECRET)
              key: url
        - name: BONFIRE_BOT
          value: "true"
      onError: continue
      volumeMounts:
        - name: artifacts
          mountPath: /artifacts
      script: |
        #!/bin/bash
        set -ex
        
        echo "Connecting to the ephemeral namespace cluster"
        login.sh

        echo "Collecting logs"
        collect-logs.sh "$(params.NS)" /artifacts || :
        minio-collect.sh "$(params.NS)" "$(params.IQE_POD)" /artifacts
    - name: release-namespace
      image: quay.io/redhat-user-workloads/rhtap-migration-tenant/bonfire-cicd-tools/cicd-tools:c66a92daeb5b9ed409e3006696572c4e62252fd4
      env:
        - name: OC_LOGIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.EPHEMERAL_ENV_PROVIDER_SECRET)
              key: token
        - name: OC_LOGIN_SERVER
          valueFrom:
            secretKeyRef:
              name: $(params.EPHEMERAL_ENV_PROVIDER_SECRET)
              key: url
        - name: BONFIRE_BOT
          value: "true"
      script: |
        #!/bin/bash
        set -ex
        
        echo "Connecting to the ephemeral namespace cluster"
        login.sh

        echo "Releasing ephemeral namespace"
        release-ns.sh "$(params.NS)" "$(params.NS_REQUESTER)"
