apiVersion: tekton.dev/v1
kind: Task
metadata:
  namespace: cost-mgmt-dev-tenant
  name: debug

spec:
  steps:
    - name: show-some-things
      image: registry.access.redhat.com/ubi9:latest
      onError: continue
      env:
        - name: PR_NUMBER
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pac.test.appstudio.openshift.io/pull-request']

      script: |
        #!/usr/bin/bash

        echo "PR number is $PR_NUMBER"
        env | sort
