apiVersion: tekton.dev/v1
kind: Task
metadata:
  namespace: cost-mgmt-dev-tenant
  name: debug

spec:
  params:
    - name: SNAPSHOT
      type: string

  steps:
    - name: show-some-things
      image: registry.access.redhat.com/ubi9:latest
      onError: continue
      env:
        - name: PR_NUMBER
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pac.test.appstudio.openshift.io/pull-request']

        - name: SNAPSHOT
          value: $(params.SNAPSHOT)

      script: |
        #!/usr/bin/bash

        env | sort
