apiVersion: tekton.dev/v1
kind: Task
metadata:
  namespace: cost-mgmt-dev-tenant
  name: debug

spec:
  params:
    - name: BONFIRE_IMAGE
      type: string

    - name: SNAPSHOT
      type: string

    - name: REF_ENV
      type: string

  steps:
    - name: show-some-things
      image: $(params.BONFIRE_IMAGE)
      onError: continue
      env:
        - name: PR_NUMBER
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pac.test.appstudio.openshift.io/pull-request']

        - name: SNAPSHOT
          value: $(params.SNAPSHOT)

        - name: REF_ENV
          value: $(params.REF_ENV)


      script: |
        #!/usr/bin/bash

        env | sort
        cat /usr/local/bin/deploy.py
