apiVersion: v1
clusters:
- cluster:
    server: https://api.stone-prd-rh01.pg1f.p1.openshiftapps.com:6443
  name: api-stone-prd-rh01-pg1f-p1-openshiftapps-com:6443
- cluster:
    server: https://api-toolchain-host-operator.apps.stone-prd-host1.wdlc.p1.openshiftapps.com//workspaces/cost-mgmt-dev
  name: konflux
contexts:
- context:
    cluster: api-stone-prd-rh01-pg1f-p1-openshiftapps-com:6443
    namespace: cost-mgmt-dev-tenant
    user: lbacciot/api-stone-prd-rh01-pg1f-p1-openshiftapps-com:6443
  name: cost-mgmt-dev-tenant/api-stone-prd-rh01-pg1f-p1-openshiftapps-com:6443/lbacciot
- context:
    cluster: konflux
    namespace: cost-mgmt-dev-tenant
    user: oidc
  name: konflux-cost-mgmt-dev
current-context: cost-mgmt-dev-tenant/api-stone-prd-rh01-pg1f-p1-openshiftapps-com:6443/lbacciot
kind: Config
preferences: {}
users:
- name: lbacciot/api-stone-prd-rh01-pg1f-p1-openshiftapps-com:6443
  user:
    token: sha256~8lfOFvvtyb1GkRNu9HdoIILiNU-fvSayFgMhzTc1erQ
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://sso.redhat.com/auth/realms/redhat-external
      - --oidc-client-id=rhoas-cli-prod
      command: kubectl
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
